//Exercise #1

When a Mule app starts a connectivity test, it runs on components such as, the HTTP or the FTP connector. They are required to connect to an external server. If the test fails, the default behavior is to log a warning message and continue with the deployment of the app instead of blocking the deployment.

You can modify this behavior by setting a number of reconnection attempts to try after an initial failure. Additionally, you can modify this behavior by forcing the deployment to fail when all connection attempts fail.

* Fail Deployment (`failsDeployment`): Forces the deployment to fail and any configured reconnection attempts are exhausted.
* Reconnect (`reconnect`): Limits the number of reconnection attempts and the interval at which to execute them. 
  For example, set a count of 5 reconnection attempts at a `frequency` of every '4000 milliseconds (ms)'. 
  This defaults to 2 reconnection attempts at a `frequency` of `2000 ms`.
  Following is a example that fails after 5 reconnection attempts are exhausted.

[source,xml]
----
<http:request-config name="HTTP_Request_Config" doc:name="HTTP Request Config">
  <http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80" >
    <reconnection failsDeployment="true" >
      <reconnect frequency="4000" count="5" />
    </reconnection
  </http:request-connection>
</http:request-config>
----

* Reconnect Forever (`reconnect-forever`): Attempts to reconnect at a given interval. For example, every 4000 ms for as long as the app runs. This defaults to every 2000 ms. However, there is no limit on the number of retries therefore, no value for count is specified.
Following is an example that does not set a limit on the number of reconnection attempts:

[source,xml]
----
<http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80" >
  <reconnection>
    <reconnect-forever frequency="4000" count=”5”/>
  </reconnection>
</http:request-connection>
----
